name: is_wear
description: A new Flutter plugin project.
version: 0.0.1


environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.litedevs.is_wear
        pluginClass: IsWearPlugin
      ios:
        pluginClass: IsWearPlugin
      macos:
        pluginClass: IsWearPlugin
      web:
        pluginClass: IsWearWeb
        fileName: is_wear_web.dart